name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.8'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.63.4
        args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.8'

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run tests with race detector
      run: go test -race -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.8'

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Build for multiple architectures
      run: |
        GOOS=linux GOARCH=amd64 go build -o mailrelay-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o mailrelay-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o mailrelay-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o mailrelay-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -o mailrelay-windows-amd64.exe .